#!/usr/bin/env bash
# Build a one-click .zip per pack.
#
# The zip is not a convenience — it is the primary distribution channel. Many
# universities put students on locked-down lab machines with no Git, and most
# professors hand out course material through an LMS (Canvas, Moodle,
# Blackboard) that takes a file, not a repository URL.
#
# Each zip unpacks to a single top-level directory named after the pack, so a
# student who unzips into their home directory gets `counter-lab/` rather than
# a scatter of loose files.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/dist"
rm -rf "$OUT"; mkdir -p "$OUT"

cd "$ROOT/packs"
for pack in */; do
  name="${pack%/}"
  [ -f "$name/pack.yaml" ] || continue
  # -x excludes: build/ is regenerated by build.sh and .DS_Store is noise.
  # -X drops extra Unix metadata Windows tooling has no use for.
  zip -qrX "$OUT/$name.zip" "$name" \
      -x "$name/build/*" -x "*/.DS_Store" -x "*/._*"
  printf "  %-28s %s\n" "$name.zip" "$(du -h "$OUT/$name.zip" | awk '{print $1}')"
done

# One archive with everything, for a professor adopting the whole curriculum.
zip -qrX "$OUT/edacrux-edu-packs-all.zip" . -x "*/build/*" -x "*/.DS_Store" -x "*/._*"
printf "  %-28s %s\n" "edacrux-edu-packs-all.zip" "$(du -h "$OUT/edacrux-edu-packs-all.zip" | awk '{print $1}')"

cd "$OUT" && shasum -a 256 *.zip > SHA256SUMS
echo ""
echo "  $(ls -1 "$OUT"/*.zip | wc -l | tr -d ' ') archives in dist/"
